---
spring:
  application:
    name: s1rates
  profiles:
    active:
    - dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SuprasannaBhaumik/cloudConfigGit
          search-paths:
          - 'station*'
        encrypt:
          enabled: false
  

server:
  port: 8888


  